# Generated by Django 5.0.2 on 2024-02-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipe_descrition',
            new_name='receipe_description',
        ),
    ]
