# Generated by Django 5.0.2 on 2024-02-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_subject_subjectmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_rank', models.IntegerField()),
            ],
        ),
    ]
